name: build

on:
  pull_request:
    types: [opened,synchronize,edited,reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 15

    - run: git update-index --chmod=+x mvnw
    - run: ./mvnw -B install --no-transfer-progress
