name: build

on:
  pull_request:
    types: [opened,synchronize,edited,reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8, 15]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{matrix.java-version}}

    - run: git update-index --chmod=+x mvnw
    - run: ./mvnw -B install --no-transfer-progress
