name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
        server-id: github

    - run: |
        git config user.email "djchally117@yahoo.com"
        git config user.name "GitHub Actions"
        git checkout -b merge
    
    - run: git update-index --chmod=+x mvnw
    - run: ./mvnw -B release:prepare release:perform --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
