name: 'On Pull Request'

on:
  pull_request:
    types: [opened,synchronize,edited,reopened]

jobs:
  Unit-Test-Run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Set up JDK 15
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
        server-id: github

    - name: Update mvnw permissions
      run: git update-index --chmod=+x mvnw

    - name: Run Unit Tests
      run: ./mvnw test
